// Imports
import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Roboto, Rufina } from "next/font/google";
import Footer from "@/components/Footer";
import Providers  from "@/components/Provider";
import { SidebarProvider } from "@/functions/context"
// Google fonts configuration
const rufina = Rufina({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-rufina",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto",
});

// Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root layout
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html
      lang="en"
      className={`${rufina.variable} ${roboto.variable}`}
    >
      <body className="max-w-[2000px] max-h-full mx-auto">
        <Providers>
          <SidebarProvider>
            <Navbar />
            {children}
            <Footer />
          </SidebarProvider>
        </Providers>
      </body>
    </html>
  );
}
